### ISSUE TITLE
first upload attempt always fails

### ISSUE THREAD

**Issue by breadguyyy** [juandjara/wafrn-rn#11]
https://github.com/user-attachments/assets/0675d9ce-5adf-4790-8215-7cbbbd85de8d

**Comment by juandjara** [comment]
okay i think i fixed this in the last build: https://expo.dev/accounts/juandjara/projects/wafrn-rn/builds/c7416aa0-e328-4ba3-8f8f-6c1f69ae3911

feel free to reopen the issue if you find the same bug again
