### ISSUE TITLE
swipe through feeds

### ISSUE THREAD

**Issue by breadguyyy** [juandjara/wafrn-rn#3]
similar to other social media apps, just allow swiping right or left to change feed

**Comment by juandjara** [comment]
Do you think this will fit with the tab layout the app has ?

The most intuituve thing I can think when swiping through the app is that it will take me to the other tabs (dashboard -> notifs -> search -> dms) and such

**Comment by breadguyyy** [comment]
on Tumblr, misskey, moshidon, reddit, and bluesky I swipe to change feed all the time so it's kind of second nature to me. swipe sideways to go from home to local to federated and back makes the most sense to me

**Comment by juandjara** [comment]
I've implemented a first version of this in this commit https://github.com/juandjara/wafrn-rn/commit/271b45cfa372a5d0770ded8a2aec0f804a497ccc so I'm going to close this issue for now
