### ISSUE TITLE
config option: proper media aspect ratio

### ISSUE THREAD

**Issue by breadguyyy** [juandjara/wafrn-rn#4]
yes this is a repeat of my discord suggestion lol but
show media uncropped in feed, ie. variable aspect ratio

**Comment by juandjara** [comment]
This is a design decision, to show all images cropped to the same ratio to reduce jumping artifacts in feeds. Now that the API has explicit width / height, we can get the real ratio for the layout and add a configuration option for toggling this, to allow all images to be showed in all their splendor, longest ones and smallest ones, as an opt-in configuration option.

Adding it as part of the developing of settings

**Comment by juandjara** [comment]
I added uncropped media by default, so lets see how it goes now. gabbo added an api with exact measures for images so it should help with latout shift. anyway, i still pretend to make this a config option

**Comment by breadguyyy** [comment]
i think we can close this one 👍
